version: '3.7'

services:
  postgres: 
    image: postgres:latest
    ports:
      - 5432:5432 # host:container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: demo
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
  api:
    image: api
    ports:
      - 8080:8080
    volumes:
      - ./.env:/.env