GET http://localhost:8080/greeting?name=Bung 

###

POST http://localhost:8080/users
Content-Type: application/json

{
    "id": 5,
    "name": "Bung Test 5"
}

###

GET http://localhost:8080/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJOYW1lIjoiT0REUyIsImV4cCI6MTcwNjY3NDk2NX0.ZJZUxxVYlJ1xZiaZ55w5LHcao6WskCsg61jfBzX6VT0

###

DELETE http://localhost:8080/users/3

###

PATCH http://localhost:8080/users/4
Content-Type: application/json

{
    "name": "Bung Patched"
}

###

GET http://localhost:8080/token

###

GET http://localhost:8080/version